name: Language Detection

on:
  push:
    branches:
      - main # Modifique para o seu ramo principal

jobs:
  detect-language:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Detect Language
        uses: actions-toolkit/languages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Utilize o token de acesso do GitHub
          path: .  # Especifique o caminho para o seu código (opcional)
